### ISSUE TITLE
Handle long RGB strips

### ISSUE THREAD

**Issue by xseignard** [vertigo-dk/BlackLED#7]
Hello,

First of all I must say I'm pretty amazed by all the work here, well done 👍 

I'm trying to adapt the code to run with ws2812 strip (and then ws2813), using the orignal OctoWS2811 lib.
I saw #6 and tried to use it with no success.
The strips I use (2 of them for now) are 5m long with 60leds/m, so each strips have 300 leds.

So I modifed the following lines (Im' running the 0.9 tagged version)
```
#define NUM_OF_OUTPUTS 2
#define MAX_NUM_LED_PER_OUTPUT 300
#define NUM_CHANNEL_PER_LED 3
...
uint32_t dmxMemory[num_led_per_output * NUM_CHANNEL_PER_LED * 2];
DMAMEM uint32_t displayMemory[num_led_per_output * NUM_CHANNEL_PER_LED * 2];
uint32_t drawingMemory[num_led_per_output * NUM_CHANNEL_PER_LED * 2];
```

And in the case of a DMX packet, I changed the following (https://github.com/vertigo-dk/BlackLED/blob/master/BlackLED.ino#L310):
```
for (int i = 0; i < 512/NUM_CHANNEL_PER_LED; i++)
```

But I still have some weird results, as if there is a "hole" of pixels not updated on my led strip.

Any idea?

Regards

**Comment by ObscuraDK** [comment]
Dear xseignard
Thank you for reaching out with this issue. I will ask my colleague Alex to look into it and get back to you. Stay tunet ;-)

**Comment by xseignard** [comment]
Hello,
Thanks for your answer! In the meantime I think I solved some stuff changing the following way of decoding the DMX data, this way both RGBW and RGB could be used. At least I think since I don't have RGBW to test here.

```
//write the dmx data to the Octo frame buffer
uint8_t* dmxData = (uint8_t*) dmx->Data;
for (int i = 0; i < 512/NUM_CHANNEL_PER_LED; i++) {
	if (NUM_CHANNEL_PER_LED == 3) {
		LEDS.setPixel(i + portOffset , dmxData[i * 3], dmxData[i * 3 + 1], dmxData[i * 3 + 2]);
	}
	else if (NUM_CHANNEL_PER_LED == 4) {
		LEDS.setPixel(i + portOffset , dmxData[i * 3], dmxData[i * 3 + 1], dmxData[i * 3 + 2], dmxData[i * 3 + 3]);
	}
}
```

I still have an issue of a led that doesn't get lit, my guess is that this led is the 170th (I haven't counted)one of the strip (eg the last one that can be addressed within an universe when RGB strips are used).

See the following picture

![img_20171117_132656](https://user-images.githubusercontent.com/515603/32947248-428bf276-cb9b-11e7-8674-d1db85395c4e.jpg)

Any idea?

Regards
